/// Daftar domain iklan dan pelacak yang diblokir oleh aplikasi.
/// Sesuai dengan spesifikasi Planning.md (Bagian 13).
const Set<String> adBlockedDomains = {
  'doubleclick.net',
  'googlesyndication.com',
  'googleadservices.com',
  'adservice.google.com',
  'adsystem.com',
  'taboola.com',
  'outbrain.com',
  'adroll.com',
  'adnxs.com',
  'criteo.com',
  'rubiconproject.com',
  'pubmatic.com',
  'casalemedia.com',
  'openx.net',
  'popads.net',
  'popcash.net',
  'propellerads.com',
  'advertising.com',
  'serving-sys.com',
  'scorecardresearch.com',
  'quantserve.com',
  'moatads.com',
  'amazon-adsystem.com',
  'admob.com',
  'ads.yahoo.com',
  'mgid.com',
  'revcontent.com',
  'zedo.com',
  'exponential.com',
};
